### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by HoffiMuc** [dzikoysk/exposed-upsert#5]
Hi,

the "manual" installation releases link doesn't work,
probably should be https://repo.panda-lang.org/#/releases/net/dzikoysk/exposed-upsert

Do you think of releasing this to central maven repository?

**Comment by dzikoysk** [comment]
Thanks, fixed :) Not really, it's easier to maintain through my repo and it's more stable, because central tends to timeout for many automated CI requests.
